services:
  froggit-gateway:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: dev
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/Berlin}
    volumes:
      - "../:/var/www/html:cached"
